version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      maven: 3.8
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase.
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/*.jar
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'